### ISSUE TITLE
remove all the join('')

### ISSUE THREAD

**Issue by kav** [lokiuz/redraft#13]
It'd be nice if redraft worked with string returning functions rather than requiring a bunch of join and recursive join functions tacked on. Happy to investigate this if there is interest.

**Comment by lokiuz** [comment]
Main focus of redraft always was rendering to directly to React components. Handling strings in nested arrays may be bit awkward if you need a pure string output.

With this in mind I don't think there's real reason to change the default output. What's possible is to add a flag to merge the output to a single string, something like:
```js
redraft(raw, renderers, { mergeOutput: true })
```

This would have to assume that all your rendering functions return strings.

**Comment by lokiuz** [comment]
Hey, I went with:
```js
redraft(raw, renderers, { joinOutput: true })
```
It joins the output and the children of all the inline and entity renderers, you still have to join the block level children seeing as a single child there can be for example a separate `<li>` tag. Also mind you have to make sure all the renderers return strings it you plan to use this option.

**Comment by lokiuz** [comment]
Rendering to string should be much simpler now, while you need to join the block level output it wont receive any nested arrays so a single `join('')` should be enough. Currently I don't see much more could be done with this, so I'm closing this.
