### ISSUE TITLE
Support complex decorators

### ISSUE THREAD

**Issue by mxstbr** [lokiuz/redraft#30]
DraftJS supports more than just simple `{ strategy, component }` decorators, specifically it supports anything matching the `DraftDecoratorType`:

https://github.com/facebook/draft-js/blob/0c609d9d3671fdbbe2a290ed160a0537f846f08e/src/model/decorators/DraftDecoratorType.js#L25-L45

As you can see, decorators can also be objects that look like this: `{ getDecorations, getComponentForKey, getPropsForKey }`. (I think interally the `{ strategy, component }` composite decorators are converted to that more complex form)

This type of decorator is (for example) used in the `draft-js-prism` decorator, but also in many other libraries. It'd be great if `redraft` supported that!

**Comment by lokiuz** [comment]
This is something worth looking into! Would like (thought it might be bit tricky) to handle it same way as draft does it internally as you suggested. 

This would probably mean that by supporting rendering with any `DraftDecoratorType` it should be possible to just fallback to drafts CompositeDraftDecorator ( https://github.com/facebook/draft-js/blob/0c609d9d3671fdbbe2a290ed160a0537f846f08e/src/model/decorators/CompositeDraftDecorator.js ) to render an array of `{ strategy, component }` decorators.

**Comment by mxstbr** [comment]
Yep that sounds great!

**Comment by lokiuz** [comment]
Guess I have a working version. :smile: 

Some things are still missing like contentState. It should be passed both to DecoratorComponent and the getDecorations method of the Decorator class.  

Additionality it adds draft-js as a dependency and I'm not sure if that makes much sense as redraft was supposed to provide an alternative way to render draft-js raw. Either I could include a simplified CompositeDraftDecorator in redraft (with no Immutable.js etc...) or go all the way include draft-js and fix most inconsistencies with the draf-js api.

Also should probably add some test cases with a custom Decorator class passed through options.

**Comment by mxstbr** [comment]
Niiice!

I'd certainly prefer if it didn't include Draft as a dependency, but obviously building your own implementation of `CompositeDraftDecorator` is going to be a bunch harder... :thinking:

**Comment by lokiuz** [comment]
Actually the `CompositeDecorator` doesn't depend much on the rest of the draft-js so implementing it in redraft was just basically swapping the `List` for a stub with a `toArray` method. 

I decided to put flow types along with it to keep the differences as minimal as possible. (Might also be a good idea to add flow to the rest of the project.)

Lastly since redraft was missing `ContentState` to pass into `getDecorations` and decorator components I added an option to pass draft-js `convertFromRaw` into redraft options.

Still need some tests.

**Comment by mxstbr** [comment]
Awesome, that's great! Can't wait for this to land, amazing work :clap:

**Comment by lokiuz** [comment]
Added some minimal testing and shipped it in 0.9.0 :tada:

**Comment by mxstbr** [comment]
Amazing, thank you! :tada:
