### ISSUE TITLE
PrismDecorator doesn't work

### ISSUE THREAD

**Issue by mxstbr** [lokiuz/redraft#33]
I just tried upgrading to `0.9.0` for complex decorator support (#30), but for some reason I'm still getting an error with `draft-js-prism`:

```JS
import Prism from 'prismjs';
import PrismDecorator from 'draft-js-prism';

const renderer = {
  decorators: [new PrismDecorator({
    prism: Prism,
    render: ({ type, children }) => <span className={`prism prism-token ${type}`}>{children}</span>
  })]
} 
```

Throws:

```
TypeError: strategy is not a function (CompositeDecorator.js:112)
  getDecorations (CompositeDecorator.js:112)
  forEach self-hosted:273:13 getDecorations (CompositeDecorator.js:98)
  decorateBlock (withDecorators.js:34)
  withDecorators (withDecorators.js:67)
  map self-hosted:297:17 withDecorators (withDecorators.js:66)
  render (render.js:231)
```

The `draft-js-prism` decorator is a complex decorator though, with `getComponentForKey`, `getDecorations`, etc.

Any ideas?

**Comment by lokiuz** [comment]
Try passing prism instance as `options.Decorator` not as part of the renderer.

I guess the documentation is not as clear on it as it should be.

**Comment by mxstbr** [comment]
Ohh, now I see that! Why wouldn't I be able to just pass that to the decorators array?

**Comment by mxstbr** [comment]
The `Decorator` option doesn't allow me to pass any options to my decorator :cry: I also have more than one complex decorator 😅 

```JS
redraft(what, ever, {
  Decorator: PrismDecorator // How do I now pass options to the PrismDecorator?!
})
```

**Comment by mxstbr** [comment]
`draft-js-plugins` has some logic to resolve an array of decorators that are a mixture of normal and complex one and make them into a single MultiDecorator here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/resolveDecorators.js

Maybe we can just use that on the `decorators` array? This ties into #32 I guess

**Comment by lokiuz** [comment]
Yeah on a first glance it looks like it would work 😄 would probably need to implement something like `MultiDecorator` from here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/MultiDecorator.js

As for passing options yeah i didn't take that into account - should accept an instance.

**Comment by lokiuz** [comment]
Switched to `MultiDecorator` instead of the Decorator option.

Published to npm with tag `next`, mind checking it out?

**Comment by mxstbr** [comment]
Can confirm that this is fixed in `redraft@next`!
