### ISSUE TITLE
Decorators incorrectly handle emojis

### ISSUE THREAD

**Issue by mxstbr** [lokiuz/redraft#34]
We're running into some bugs around decorating text that has emojis in it. Since a screenshot is worth a thousand words:

![screen shot 2017-11-20 at 12 13 00 pm](https://user-images.githubusercontent.com/7525670/33015881-a7b56792-cdec-11e7-817b-50616a5236ee.png)

Note how the `@rauchg` mention is misaligned by a couple of characters. However, if the emoji is removed from the initial text it all works perfectly:

![screen shot 2017-11-20 at 12 14 35 pm](https://user-images.githubusercontent.com/7525670/33015911-c8ca77ce-cdec-11e7-854d-08ab58cc303e.png)

Running `redraft@0.9.0`. Since I'm a nice open source citizen™️ here you have a full reproduction of the bug to play around with: https://codesandbox.io/s/y2rpn3py3x

**Comment by lokiuz** [comment]
Good catch!

Should be fixed now.
Bumped version to 0.9.1-beta2 here: https://9ow1j8q1zp.codesandbox.io/
(This version also should have #33 resolved)

**Comment by mxstbr** [comment]
I can confirm this is fixed by upgrading to `0.9.1-beta2`!

![screen shot 2017-11-21 at 12 08 23 pm](https://user-images.githubusercontent.com/7525670/33069398-bbfc4ea0-ceb4-11e7-89c6-3aee5db32389.png)
