### ISSUE TITLE
ReactNative support

### ISSUE THREAD

**Issue by mxstbr** [lokiuz/redraft#35]
Unsure if this works right now, but does redraft have ReactNative support? Can I just return `<View />`s instead of `<div />`s?

**Comment by lokiuz** [comment]
Didn't have a chance to test it myself yet as I only played around with RN a bit, but it should work just fine. Redraft itself doesn't have any React specific code/dependencies.

Might be a good idea to test it and add some info to readme.

**Comment by mxstbr** [comment]
Running into the first issue:

<img width="559" alt="screen shot 2018-01-22 at 11 07 55" src="https://user-images.githubusercontent.com/7525670/35215580-fb23e3f0-ff64-11e7-9ab7-28a2650ab1e4.png">

How can I make sure that redraft never returns just a string? In ReactNative you _have_ to wrap every string in a `Text` component.

This is what my renderer look like so far:

```JS
import React from 'react';
import Text from '../components/Text';

const renderer = {
  blocks: {
    unstyled: (children, { keys }) =>
      children.map((child, index) => (
        <Text key={keys[index] || index}>{child}</Text>
      )),
    'header-one': (children, { keys }) =>
      children.map((child, index) => (
        <Text type="title1" key={keys[index] || index}>{child}</Text>
      )),
    'header-two': (children, { keys }) =>
      children.map((child, index) => (
        <Text type="title2" key={keys[index] || index}>{child}</Text>
      )),
  },
};
```

**Comment by mxstbr** [comment]
Worked around this for now by doing

```JS
const filterStrings = (array) => {
  const items = [];
  array.forEach(item => {
    if (typeof item === 'string') return;
    if (Array.isArray(item)) return items.push(filterStrings(item));

    items.push(item);
  })

  return items;
}

filterStrings(redraft(state, renderer));
```

The solution to this could be a `unknownMap` option to wrap each unknown type in an `unstyled` block maybe? That would work for our use case.

**Comment by lokiuz** [comment]
If I understand this correctly your raw contains a block that doesn't have a corresponding renderer which results in the block being returned as a string. 

Falling back to unstyled might be an option, or possibly allow to define a custom fallback type.

**Comment by mxstbr** [comment]
Yesss, that is perfect! Did you release the `blockFallback` option already?

**Comment by lokiuz** [comment]
I just did 0.10.0 release as this changes the default behavior. Should I close this for now?

**Comment by mxstbr** [comment]
Sounds good!
