### ISSUE TITLE
Persist multiple spaces between text?

### ISSUE THREAD

**Issue by nicubarbaros** [lokiuz/redraft#36]
Hey there. Thank you for the plugin. 

Can the multiple spaces between text be persisted? I could not find any options.

Here is a [GIF](http://www.giphy.com/gifs/l1IBiRxDKN6fOQwZq) that shows what I mean.

**Comment by lokiuz** [comment]
The white-space characters get collapsed by default. Try adding something like `white-space: pre;` to your css. It can be either on the element itself or higher up.

More info here:
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by nicubarbaros** [comment]
Wohh, never thought of that. Thank you. Though I should have the look into the render HTML and see that the spaces are there. Thank you.

**Comment by lokiuz** [comment]
You're welcome 😃

**Comment by nicubarbaros** [comment]
For those that check this issue. Add     `white-space: pre-wrap` this way it will preserve spaces and wrap to new lines (as editor js does)
